DATASET:
  TYPE: ObjectNav-v1
  SPLIT: train
  DATA_PATH: /private/home/mikaelhenaff/projects/genexp/habitat-challenge/habitat-lab/data/datasets/objectnav_hm3d_v1/{split}/{split}.json.gz
#  DATA_PATH: data/datasets/objectnav/hm3d/v1/{split}/{split}.json.gz
